### ISSUE TITLE
Error when installing from network

### ISSUE THREAD

**Issue by SageStarCodes** [OpenPrograms/Plan9k#9]
![2017-01-02_18 48 05](https://cloud.githubusercontent.com/assets/1764903/21593846/23f941bc-d11c-11e6-9d0f-ec3fd4cf7fae.png)

This is in the Direwolf20 1.10.2 modpack, IDK the version of OC in the pack.

**Comment by magik6k** [comment]
I assume it has old MPT as it was issue with it. As a workaround do the following:
```
cd /
wget http://mpt.magik6k.net/file/mpt/usr/bin/mpt.lua /tmp/mpt.lua
/tmp/mpt.lua -Syv plan9k-extra --root=/mnt/[3 first characters of hard drive ID]
```

This should work.
